// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eugene.hotelproj.models;

import com.eugene.hotelproj.models.HotelUser;
import com.eugene.hotelproj.models.HotelUserDataOnDemand;
import com.eugene.hotelproj.models.UserProfileDataOnDemand;
import com.eugene.hotelproj.models.UserRoleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect HotelUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: HotelUserDataOnDemand: @Component;
    
    private Random HotelUserDataOnDemand.rnd = new SecureRandom();
    
    private List<HotelUser> HotelUserDataOnDemand.data;
    
    @Autowired
    UserProfileDataOnDemand HotelUserDataOnDemand.userProfileDataOnDemand;
    
    @Autowired
    UserRoleDataOnDemand HotelUserDataOnDemand.userRoleDataOnDemand;
    
    public HotelUser HotelUserDataOnDemand.getNewTransientHotelUser(int index) {
        HotelUser obj = new HotelUser();
        setPassword(obj, index);
        setUserName(obj, index);
        return obj;
    }
    
    public void HotelUserDataOnDemand.setPassword(HotelUser obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void HotelUserDataOnDemand.setUserName(HotelUser obj, int index) {
        String userName = "userName_" + index;
        obj.setUserName(userName);
    }
    
    public HotelUser HotelUserDataOnDemand.getSpecificHotelUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        HotelUser obj = data.get(index);
        Long id = obj.getId();
        return HotelUser.findHotelUser(id);
    }
    
    public HotelUser HotelUserDataOnDemand.getRandomHotelUser() {
        init();
        HotelUser obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return HotelUser.findHotelUser(id);
    }
    
    public boolean HotelUserDataOnDemand.modifyHotelUser(HotelUser obj) {
        return false;
    }
    
    public void HotelUserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = HotelUser.findHotelUserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'HotelUser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<HotelUser>();
        for (int i = 0; i < 10; i++) {
            HotelUser obj = getNewTransientHotelUser(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
