// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eugene.hotelproj.models;

import com.eugene.hotelproj.models.HotelUser;
import com.eugene.hotelproj.models.HotelUserDataOnDemand;
import com.eugene.hotelproj.models.HotelUserIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HotelUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HotelUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HotelUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HotelUserIntegrationTest: @Transactional;
    
    @Autowired
    HotelUserDataOnDemand HotelUserIntegrationTest.dod;
    
    @Test
    public void HotelUserIntegrationTest.testCountHotelUsers() {
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to initialize correctly", dod.getRandomHotelUser());
        long count = HotelUser.countHotelUsers();
        Assert.assertTrue("Counter for 'HotelUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HotelUserIntegrationTest.testFindHotelUser() {
        HotelUser obj = dod.getRandomHotelUser();
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to provide an identifier", id);
        obj = HotelUser.findHotelUser(id);
        Assert.assertNotNull("Find method for 'HotelUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HotelUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HotelUserIntegrationTest.testFindAllHotelUsers() {
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to initialize correctly", dod.getRandomHotelUser());
        long count = HotelUser.countHotelUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'HotelUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HotelUser> result = HotelUser.findAllHotelUsers();
        Assert.assertNotNull("Find all method for 'HotelUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HotelUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HotelUserIntegrationTest.testFindHotelUserEntries() {
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to initialize correctly", dod.getRandomHotelUser());
        long count = HotelUser.countHotelUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HotelUser> result = HotelUser.findHotelUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HotelUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HotelUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HotelUserIntegrationTest.testFlush() {
        HotelUser obj = dod.getRandomHotelUser();
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to provide an identifier", id);
        obj = HotelUser.findHotelUser(id);
        Assert.assertNotNull("Find method for 'HotelUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHotelUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'HotelUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HotelUserIntegrationTest.testMergeUpdate() {
        HotelUser obj = dod.getRandomHotelUser();
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to provide an identifier", id);
        obj = HotelUser.findHotelUser(id);
        boolean modified =  dod.modifyHotelUser(obj);
        Integer currentVersion = obj.getVersion();
        HotelUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'HotelUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HotelUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to initialize correctly", dod.getRandomHotelUser());
        HotelUser obj = dod.getNewTransientHotelUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HotelUser' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'HotelUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HotelUserIntegrationTest.testRemove() {
        HotelUser obj = dod.getRandomHotelUser();
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HotelUser' failed to provide an identifier", id);
        obj = HotelUser.findHotelUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HotelUser' with identifier '" + id + "'", HotelUser.findHotelUser(id));
    }
    
}
