// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eugene.hotelproj.models;

import com.eugene.hotelproj.models.Reservation;
import com.eugene.hotelproj.models.ReservationDataOnDemand;
import com.eugene.hotelproj.models.RoomDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ReservationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReservationDataOnDemand: @Component;
    
    private Random ReservationDataOnDemand.rnd = new SecureRandom();
    
    private List<Reservation> ReservationDataOnDemand.data;
    
    @Autowired
    RoomDataOnDemand ReservationDataOnDemand.roomDataOnDemand;
    
    public Reservation ReservationDataOnDemand.getNewTransientReservation(int index) {
        Reservation obj = new Reservation();
        setDateIn(obj, index);
        setDateOut(obj, index);
        return obj;
    }
    
    public void ReservationDataOnDemand.setDateIn(Reservation obj, int index) {
        Date dateIn = new Date(new Date().getTime() + 10000000L);
        obj.setDateIn(dateIn);
    }
    
    public void ReservationDataOnDemand.setDateOut(Reservation obj, int index) {
        Date dateOut = new Date(new Date().getTime() + 10000000L);
        obj.setDateOut(dateOut);
    }
    
    public Reservation ReservationDataOnDemand.getSpecificReservation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Reservation obj = data.get(index);
        Long id = obj.getId();
        return Reservation.findReservation(id);
    }
    
    public Reservation ReservationDataOnDemand.getRandomReservation() {
        init();
        Reservation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Reservation.findReservation(id);
    }
    
    public boolean ReservationDataOnDemand.modifyReservation(Reservation obj) {
        return false;
    }
    
    public void ReservationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Reservation.findReservationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Reservation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Reservation>();
        for (int i = 0; i < 10; i++) {
            Reservation obj = getNewTransientReservation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
