// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eugene.hotelproj.models;

import com.eugene.hotelproj.models.Reserved;
import com.eugene.hotelproj.models.ReservedDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ReservedDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReservedDataOnDemand: @Component;
    
    private Random ReservedDataOnDemand.rnd = new SecureRandom();
    
    private List<Reserved> ReservedDataOnDemand.data;
    
    public Reserved ReservedDataOnDemand.getNewTransientReserved(int index) {
        Reserved obj = new Reserved();
        return obj;
    }
    
    public Reserved ReservedDataOnDemand.getSpecificReserved(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Reserved obj = data.get(index);
        Long id = obj.getId();
        return Reserved.findReserved(id);
    }
    
    public Reserved ReservedDataOnDemand.getRandomReserved() {
        init();
        Reserved obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Reserved.findReserved(id);
    }
    
    public boolean ReservedDataOnDemand.modifyReserved(Reserved obj) {
        return false;
    }
    
    public void ReservedDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Reserved.findReservedEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Reserved' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Reserved>();
        for (int i = 0; i < 10; i++) {
            Reserved obj = getNewTransientReserved(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
