// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eugene.hotelproj.models;

import com.eugene.hotelproj.models.ReservationIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ReservationIntegrationTest_Roo_Configurable {
    
    declare @type: ReservationIntegrationTest: @Configurable;
    
}
