// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eugene.hotelproj.models;

import com.eugene.hotelproj.models.RoomType;
import com.eugene.hotelproj.models.RoomTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RoomTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RoomTypeDataOnDemand: @Component;
    
    private Random RoomTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<RoomType> RoomTypeDataOnDemand.data;
    
    public RoomType RoomTypeDataOnDemand.getNewTransientRoomType(int index) {
        RoomType obj = new RoomType();
        return obj;
    }
    
    public RoomType RoomTypeDataOnDemand.getSpecificRoomType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        RoomType obj = data.get(index);
        Long id = obj.getId();
        return RoomType.findRoomType(id);
    }
    
    public RoomType RoomTypeDataOnDemand.getRandomRoomType() {
        init();
        RoomType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return RoomType.findRoomType(id);
    }
    
    public boolean RoomTypeDataOnDemand.modifyRoomType(RoomType obj) {
        return false;
    }
    
    public void RoomTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = RoomType.findRoomTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'RoomType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<RoomType>();
        for (int i = 0; i < 10; i++) {
            RoomType obj = getNewTransientRoomType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
