// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eugene.hotelproj.models;

import com.eugene.hotelproj.models.UserProfile;
import com.eugene.hotelproj.models.UserProfileDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserProfileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserProfileDataOnDemand: @Component;
    
    private Random UserProfileDataOnDemand.rnd = new SecureRandom();
    
    private List<UserProfile> UserProfileDataOnDemand.data;
    
    public UserProfile UserProfileDataOnDemand.getNewTransientUserProfile(int index) {
        UserProfile obj = new UserProfile();
        setCity(obj, index);
        setCountry(obj, index);
        setFatherName(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        setMail(obj, index);
        setPhoneNumber(obj, index);
        setSkype(obj, index);
        return obj;
    }
    
    public void UserProfileDataOnDemand.setCity(UserProfile obj, int index) {
        String city = "city_" + index;
        obj.setCity(city);
    }
    
    public void UserProfileDataOnDemand.setCountry(UserProfile obj, int index) {
        String country = "country_" + index;
        obj.setCountry(country);
    }
    
    public void UserProfileDataOnDemand.setFatherName(UserProfile obj, int index) {
        String fatherName = "fatherName_" + index;
        obj.setFatherName(fatherName);
    }
    
    public void UserProfileDataOnDemand.setFirstName(UserProfile obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void UserProfileDataOnDemand.setLastName(UserProfile obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void UserProfileDataOnDemand.setMail(UserProfile obj, int index) {
        String mail = "foo" + index + "@bar.com";
        obj.setMail(mail);
    }
    
    public void UserProfileDataOnDemand.setPhoneNumber(UserProfile obj, int index) {
        String phoneNumber = "phoneNumber_" + index;
        obj.setPhoneNumber(phoneNumber);
    }
    
    public void UserProfileDataOnDemand.setSkype(UserProfile obj, int index) {
        String skype = "skype_" + index;
        obj.setSkype(skype);
    }
    
    public UserProfile UserProfileDataOnDemand.getSpecificUserProfile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserProfile obj = data.get(index);
        Long id = obj.getUserProfileId();
        return UserProfile.findUserProfile(id);
    }
    
    public UserProfile UserProfileDataOnDemand.getRandomUserProfile() {
        init();
        UserProfile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getUserProfileId();
        return UserProfile.findUserProfile(id);
    }
    
    public boolean UserProfileDataOnDemand.modifyUserProfile(UserProfile obj) {
        return false;
    }
    
    public void UserProfileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserProfile.findUserProfileEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserProfile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserProfile>();
        for (int i = 0; i < 10; i++) {
            UserProfile obj = getNewTransientUserProfile(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
